name: Container Build

description: コンテナイメージをビルドし、ECRへプッシュします。

inputs:
  ecr-repository-uri:
    required: true
    description: ECRリポジトリのURI
  dockerfile-path:
    required: true
    description: Dockerfileのパス

outputs:
  container-image:
    value: ${{ steps.meta.outputs.tags }}
    description: ビルドしたコンテナイメージ

runs:
  using: composite
  steps:
    - name: ECRにログイン
      uses: aws-actions/amazon-ecr-login@v2

    - name: コンテナイメージのメタデータ生成
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: type=sha,format=long

    - name: イメージのビルド
      run: |
        ###### dockerコマンドを使用してビルドしてください  ヒント1参照      ######
        ###### Dockerfileは${{ inputs.dockerfile-path }}を使ってください  ######
        ###### タグには${{ steps.meta.outputs.tags }}が使えます           ######
        docker build -f ${{ inputs.dockerfile-path }} -t ${{ steps.meta.outputs.tags }} .
        
      shell: bash

    - name: ECRにイメージをプッシュ
      if: success()
      run: |
        ###### dockerコマンドを使用してECRにプッシュしてください。  ヒント2参照 ######
        docker push ${{ steps.meta.outputs.tags }}
      shell: bash